### ISSUE TITLE
誤記のご連絡

### ISSUE THREAD

**Issue by mitkz** [plotly-dash-book/plotly-dash-book#13]
こんにちは！楽しく読ませて頂いています！ 
p60 3.2.4 2次元ヒストグラムの項の説明文で、2次元ヒストグラム（等高線）を描画するクラスの名前が

> Histogram2dCountour

となっていますが、正しくは
> Histogram2dContour

ではないでしょうか？ 
細かくてすみませんが、ご確認よろしくお願いいたします🙇‍♂️

**Comment by drillan** [comment]
ご指摘ありがとうございます。
誤植でしたので、 [正誤表](https://github.com/plotly-dash-book/plotly-dash-book/blob/master/SEIGO.md) に記載しました。
次刷にて対応する予定です。
