### ISSUE TITLE
誤記の連絡（p.46に記載のコードについて）

### ISSUE THREAD

**Issue by HisayaMiyao** [plotly-dash-book/plotly-dash-book#15]
こんにちは、大変ためになる書籍を執筆頂きありがとうございます。
細かいところで恐縮ですが、気づいたところがありますのでこちらで報告させて頂きます。

初版第2刷のp.46の下部に記載されているソースコードが、続くp.47にあるものと同一になっているようです。
こちらのリポジトリにあるコードは正しいものになっているようですので、書籍上の誤りかと思います。

以上です、ご参考まで。

**Comment by drillan** [comment]
ご連絡ありがとうございます
現在3刷の準備をしていたところなので、3刷にて該当箇所を修正します
大変助かりました、取り急ぎお礼まで

**Comment by drillan** [comment]
3刷で対応済み
